# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e811a97987726a41d87e0944f0665cacf2269408a0724400f20a341247ce33f6fb9642b7191c5d0b37eb6a92f878e7ec19983f65e44db4a85423575c1da46062

test:
  secret_key_base: e6f853282ec1df1d285b11506d010912602ac1d8d8e649fac073c727f0ff3222c7c915c362598b9f896a6cf0d073cbfc4e1ef3dd5aedf0a721c811c7a873a974

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
